# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-iiot-gateway"
BBFILE_PATTERN_meta-iiot-gateway = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-iiot-gateway = "10"

LAYERDEPENDS_meta-iiot-gateway = "core openembedded-layer rauc"
LAYERSERIES_COMPAT_meta-iiot-gateway = "kirkstone scarthgap"
